-- =============================================================
-- LOCAL HACKATHON SURROGATE
-- Mirrors DDS field names for mock adapter use.
-- NOT equivalent to Db2 for i runtime semantics.
-- Field names match orderpro/dds/ definitions exactly.
-- Types are SQLite-compatible approximations only.
-- =============================================================

CREATE TABLE IF NOT EXISTS CUSMAS (
    CUSNUM  INTEGER  NOT NULL,
    CUSNAM  TEXT     NOT NULL DEFAULT '',
    CUSADR  TEXT     NOT NULL DEFAULT '',
    CUSCLS  TEXT     NOT NULL DEFAULT 'S',
    CUSCRL  REAL     NOT NULL DEFAULT 0,
    CUSSTT  TEXT     NOT NULL DEFAULT 'A',
    PRIMARY KEY (CUSNUM)
);

CREATE TABLE IF NOT EXISTS ORDHED (
    ORDNUM  INTEGER  NOT NULL,
    CUSNUM  INTEGER  NOT NULL,
    ORDDAT  INTEGER  NOT NULL DEFAULT 0,
    ORDTIM  INTEGER  NOT NULL DEFAULT 0,
    ORDTYP  TEXT     NOT NULL DEFAULT 'S',
    ORDSTS  TEXT     NOT NULL DEFAULT 'O',
    ORDTOT  REAL     NOT NULL DEFAULT 0,
    PRIMARY KEY (ORDNUM),
    FOREIGN KEY (CUSNUM) REFERENCES CUSMAS(CUSNUM)
);

CREATE TABLE IF NOT EXISTS ORDLIN (
    ORDNUM  INTEGER  NOT NULL,
    LINNUM  INTEGER  NOT NULL,
    ITMNUM  TEXT     NOT NULL DEFAULT '',
    LINQTY  INTEGER  NOT NULL DEFAULT 0,
    LINPRC  REAL     NOT NULL DEFAULT 0,
    LINAMT  REAL     NOT NULL DEFAULT 0,
    PRIMARY KEY (ORDNUM, LINNUM),
    FOREIGN KEY (ORDNUM) REFERENCES ORDHED(ORDNUM)
);

CREATE TABLE IF NOT EXISTS INVMAS (
    ITMNUM  TEXT     NOT NULL,
    ITMDSC  TEXT     NOT NULL DEFAULT '',
    QTYOH   INTEGER  NOT NULL DEFAULT 0,
    QTYALC  INTEGER  NOT NULL DEFAULT 0,
    QTYAVL  INTEGER  NOT NULL DEFAULT 0,
    ITMSTS  TEXT     NOT NULL DEFAULT 'A',
    PRIMARY KEY (ITMNUM)
);
