'use strict';

const { EVIDENCE_BASIS, STATUS } = require('../evidence/model');

function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function countBy(items, key) {
  return items.reduce((acc, item) => {
    const value = item[key] || 'UNKNOWN';
    acc[value] = (acc[value] || 0) + 1;
    return acc;
  }, {});
}

function primary(findings) {
  const inferred = findings.filter(f => f.evidenceBasis === EVIDENCE_BASIS.INFERRED);
  const byArtifact = new Map();
  findings.filter(f => f.evidenceBasis === EVIDENCE_BASIS.OBSERVED_SOURCE).forEach(f => {
    const previous = byArtifact.get(f.artifact);
    if (!previous || (f.relevanceScore || 0) > (previous.relevanceScore || 0)) byArtifact.set(f.artifact, f);
  });
  const tests = findings.filter(f => f.artifactType === 'TEST');
  return [...inferred, ...byArtifact.values(), ...tests];
}

function renderMarkdown(findings, changeRequest, profile, diffResult) {
  const lines = [];
  const basis = countBy(findings, 'evidenceBasis');
  const status = countBy(findings, 'status');
  const target = countBy(findings, 'validationTarget');
  const tests = findings.filter(f => f.artifactType === 'TEST');
  const passing = tests.filter(f => f.status === STATUS.RESOLVED).length;
  const failing = tests.filter(f => f.status === STATUS.OPEN).length;
  const pending = tests.filter(f => f.status === STATUS.TARGET_VALIDATION_REQUIRED).length;

  lines.push(`# ChangeProof Evidence Pack — ${profile.name}`);
  lines.push('');
  lines.push(`**Workload profile:** \`${profile.id}\``);
  lines.push(`**Scenario:** ${profile.description}`);
  lines.push('');
  lines.push('> Generated by the workload-neutral ChangeProof evidence core. Scenario-specific behavior is supplied through a profile and inference plug-in, not hard-coded into the core.');
  lines.push('');
  lines.push('## Change request');
  lines.push('');
  lines.push(changeRequest.trim());
  lines.push('');
  lines.push('## Evidence summary');
  lines.push('');
  lines.push(`- Total findings: **${findings.length}**`);
  lines.push(`- Tests: **${passing} passing / ${failing} failing / ${pending} pending**`);
  lines.push(`- evidenceBasis: ${Object.entries(basis).map(([k,v]) => `${k}=${v}`).join(', ')}`);
  lines.push(`- status: ${Object.entries(status).map(([k,v]) => `${k}=${v}`).join(', ')}`);
  lines.push(`- validationTarget: ${Object.entries(target).map(([k,v]) => `${k}=${v}`).join(', ')}`);
  lines.push('');
  lines.push('## Primary review chain');
  lines.push('');
  lines.push('| Artifact | Symbol | Evidence basis | Status | Target | Finding |');
  lines.push('|---|---|---|---|---|---|');
  primary(findings).forEach(f => lines.push(`| \`${f.artifact}\` | ${f.symbol} | ${f.evidenceBasis} | ${f.status} | ${f.validationTarget} | ${String(f.finding).replace(/\|/g,'\\|')} |`));

  if (diffResult) {
    lines.push('');
    lines.push('## Diff summary');
    lines.push('');
    lines.push(`- Resolved: **${diffResult.resolved.length}**`);
    lines.push(`- Persisted: **${diffResult.persisted.length}**`);
    lines.push(`- Target validation required: **${diffResult.targetValidationRequired.length}**`);
    lines.push(`- New findings: **${diffResult.newFindings.length}**`);
  }

  return lines.join('\n');
}

function renderHtml(findings, changeRequest, profile, diffResult) {
  const basis = countBy(findings, 'evidenceBasis');
  const status = countBy(findings, 'status');
  const target = countBy(findings, 'validationTarget');
  const tests = findings.filter(f => f.artifactType === 'TEST');
  const passing = tests.filter(f => f.status === STATUS.RESOLVED).length;
  const failing = tests.filter(f => f.status === STATUS.OPEN).length;
  const pending = tests.filter(f => f.status === STATUS.TARGET_VALIDATION_REQUIRED).length;
  const rows = primary(findings).map(f => `<tr><td><code>${esc(f.artifact)}</code></td><td>${esc(f.symbol)}</td><td><span class="basis ${esc(f.evidenceBasis)}">${esc(f.evidenceBasis)}</span></td><td>${esc(f.status)}</td><td>${esc(f.validationTarget)}</td><td>${esc(f.finding)}</td></tr>`).join('');
  const diff = diffResult ? `<section><h2>Diff summary</h2><div class="metrics"><div><b>${diffResult.resolved.length}</b><span>resolved</span></div><div><b>${diffResult.persisted.length}</b><span>persisted</span></div><div><b>${diffResult.targetValidationRequired.length}</b><span>target validation</span></div><div><b>${diffResult.newFindings.length}</b><span>new</span></div></div></section>` : '';

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ChangeProof — ${esc(profile.name)}</title><style>
  :root{color-scheme:dark;--bg:#07100c;--panel:#0b1710;--line:#274332;--text:#dcebe0;--muted:#87a08f;--green:#7fffb2;--amber:#f2b84b;--blue:#76a9ff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,Segoe UI,system-ui,sans-serif;font-size:14px;line-height:1.55}main{max-width:1180px;margin:0 auto;padding:44px 24px 70px}header{border-bottom:1px solid var(--line);padding-bottom:24px;margin-bottom:24px}header p{color:var(--muted);max-width:850px}code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--green)}.eyebrow{font:600 11px ui-monospace,monospace;letter-spacing:.11em;text-transform:uppercase;color:var(--green)}h1{font-size:32px;margin:.3rem 0}h2{font-size:18px;margin:32px 0 12px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.metrics div,.summary div{border:1px solid var(--line);background:var(--panel);padding:14px}.metrics b{display:block;font:400 25px ui-monospace,monospace}.metrics span,.summary span{color:var(--muted);font-size:12px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.summary b{display:block;margin-top:5px;font:500 12px ui-monospace,monospace;color:var(--green)}pre{background:#030805;border:1px solid var(--line);padding:16px;white-space:pre-wrap;overflow:auto;color:#b8cbbb}table{width:100%;border-collapse:collapse;font-size:12px}th{text-align:left;color:var(--muted);font-weight:600;background:#0c1811}th,td{border:1px solid var(--line);padding:8px;vertical-align:top}.basis{font:600 10px ui-monospace,monospace}.basis.INFERRED{color:var(--amber)}.basis.EXECUTED_LOCAL{color:var(--green)}.basis.OBSERVED_SOURCE{color:var(--blue)}.core-note{border-left:2px solid var(--green);padding:12px 14px;background:rgba(127,255,178,.04);color:#aabfae}@media(max-width:760px){.metrics,.summary{grid-template-columns:1fr 1fr}table{display:block;overflow-x:auto}}
  </style></head><body><main><header><div class="eyebrow">ChangeProof / reusable workload profile</div><h1>${esc(profile.name)}</h1><p>${esc(profile.description)}</p><p class="core-note">Generated by the workload-neutral ChangeProof evidence core. Scenario-specific source scope and inference are supplied by the <code>${esc(profile.id)}</code> profile.</p></header><section><h2>Change request</h2><pre>${esc(changeRequest.trim())}</pre></section><section><h2>Evidence summary</h2><div class="metrics"><div><b>${findings.length}</b><span>findings</span></div><div><b>${passing}</b><span>passing tests</span></div><div><b>${failing}</b><span>failing tests</span></div><div><b>${pending}</b><span>pending tests</span></div></div><div class="summary"><div><span>evidenceBasis</span><b>${esc(Object.entries(basis).map(([k,v])=>`${k} ${v}`).join(' · '))}</b></div><div><span>status</span><b>${esc(Object.entries(status).map(([k,v])=>`${k} ${v}`).join(' · '))}</b></div><div><span>validationTarget</span><b>${esc(Object.entries(target).map(([k,v])=>`${k} ${v}`).join(' · '))}</b></div></div></section><section><h2>Primary review chain</h2><table><thead><tr><th>Artifact</th><th>Symbol</th><th>Basis</th><th>Status</th><th>Target</th><th>Finding</th></tr></thead><tbody>${rows}</tbody></table></section>${diff}<section><h2>Machine-readable evidence</h2><p>Every row above is emitted to the adjacent <code>traceability.json</code>. The HTML is a review surface, not the source of truth.</p></section></main></body></html>`;
}

module.exports = { renderMarkdown, renderHtml };
